SELECT
    I.Company,
    FG.Goal,
    COUNT(*) as GoalCount
FROM INVESTOR I
JOIN FINANCIAL_GOAL FG ON I.Phone = FG.Phone
WHERE DATEDIFF(YEAR, I.DoB, GETDATE()) BETWEEN 30 AND 40
GROUP BY I.Company, FG.Goal
ORDER BY I.Company, GoalCount DESC;